---
title: "Select universe"
author: "Zuguang Gu ( z.gu@dkfz.de )"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    fig_caption: true
---

```{r, echo = FALSE, message = FALSE}
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.align = "center"
)
```


```{r}
source("lib.R")
```


```{r, fig.width = 6, fig.height = 6}
country_meta = read.table("country_meta.tab", sep = "\t", quote = "", header = TRUE)
country_meta = country_meta[!duplicated(country_meta$standardName), ]
country_meta$subregion2 = ifelse(grepl(", ", country_meta$subregion), gsub("^.*, ", "", country_meta$subregion), NA)
country_meta$subregion = gsub(", .*$", "", country_meta$subregion)
rownames(country_meta) = country_meta$standardName
country_meta = country_meta[, c("officialName", "region", "subregion", "subregion2")]
head(country_meta)


df = read.table("num_cite_country_country.tab", quote = "", sep = "\t", header = TRUE)
n_cited = tapply(df[, 3], df[, 1], sum)
n_citing = tapply(df[, 3], df[, 2], sum)


df = read.table("num_cite_country_country.tab", quote = "", sep = "\t", header = TRUE)
df1 = calc_stat(df, all = FALSE); rownames(df1) = paste(df1[, 1], df1[, 2], sep = "-")
df2 = df[df[, 1] != df[, 2], ]
df2 = calc_stat(df2, all = FALSE); rownames(df2) = paste(df2[, 1], df2[, 2], sep = "-")

cn = intersect(rownames(df1), rownames(df2))
df1 = df1[cn, ]
df2 = df2[cn, ]

l = df1$log2_fc- df2$log2_fc < -0.4
plot(df1$log2_fc, df2$log2_fc, cex = ifelse(l, 0.8, 0.2), 
	col = circlize::add_transparency(ifelse(l&grepl("United States", rownames(df1)), "red", 
		      ifelse(l&grepl("China", rownames(df1)), "blue", 
		      	ifelse(l&grepl("Ethiopia", rownames(df1)), "orange", "black"))), 0.25),
	pch = ifelse(df1$country_cited == "United States", 4, 
		      ifelse(df1$country_cited == "China", 4,
		      	 ifelse(df1$country_cited == "Ethiopia", 4, 16))
		),
	xlab = "log2 fold enrichment / all citations", ylab = "log2 fold enrichment / international citations", main = "compare universe"
)
abline(v = 0, lty = 2, col = "grey")
abline(h = 0, lty = 2, col = "grey")
legend("topleft", cex = 0.7,
	legend = c("from United States", "on United States", "on China", "on Ethiopia", "others"), 
	col = c("red", "red", "blue", "orange", "black"), pch = c(16, 4, 4, 4, 16))
```



```{r, fig.width = 10, fig.height = 10}
df = read.table("num_cite_country_country.tab", quote = "", sep = "\t", header = TRUE)
df = df[df[, 1] != df[, 2], ]
df = calc_stat(df, cutoff_total = 10000, cutoff_single = 100, min_country = 24, all = FALSE)
m = xtabs(log2_fc ~ country_cited + country_citing, data = df)
class(m) = "matrix"


all_countries = rownames(m)

m2 = m
m2[m2 < 0] = 0
library(igraph)

set.seed(123)
g = graph_from_adjacency_matrix(m2, mode = "plus", weighted = TRUE)
cm = cluster_louvain(g, weight = E(g)$weight, resolution = 1.2)
communities(cm)
mem = membership(cm)

region_color = structure(RColorBrewer::brewer.pal(length(unique(country_meta$region)), "Set3"), names = unique(country_meta$region))

library(ComplexHeatmap)

robust_dist_pair = function(x, y, trim = 0.1) {
	x_mid = mean(x, na.rm = TRUE)
	y_mid = mean(y, na.rm = TRUE)

	dd = sqrt( (x-x_mid)^2 + (y-y_mid)^2 )

	q = quantile(dd, c(trim/2, 1-trim/2), na.rm = TRUE)
	l = dd >= q[1] & dd <= q[2]
	l[is.na(l)] = FALSE
	sqrt( sum( (x[l] - y[l])^2 ) )/sum(l)
}

robust_dist = function(m, trim = 0.1) {
	n = nrow(m)
	d = matrix(0, nrow = n, ncol = n)
	rownames(d) = colnames(d) = rownames(m)

	for(i in 1:(n-1)) {
		for(j in (i+1):n) {
			d[i, j] = d[j, i] = robust_dist_pair(m[i, ], m[j, ], trim = trim)
		}
	}

	as.dist(d)
}

m_with_NA = m
m_with_NA[m == 0] = NA

row_order = order.dendrogram(reorder(as.dendrogram(hclust(robust_dist(m_with_NA))), -rowMeans(m_with_NA, na.rm = TRUE)))
col_order = order.dendrogram(reorder(as.dendrogram(hclust(robust_dist(t(m_with_NA)))), -colMeans(m_with_NA, na.rm = TRUE)))

ht = Heatmap(m, name = "Enrichment score", #cluster_rows = hc, cluster_columns = hc,
	row_title = "Cited/influencing countries",
	column_title = "Citing/influenced countries", column_title_side = "bottom",
	row_order = row_order, column_order = col_order, row_names_side = "left",
	row_names_gp = gpar(fontsize = 8),
	column_names_gp = gpar(fontsize = 8),
	layer_fun = function(j, i, x, y, w, h, fill) {
		l = pindex(m, i, j) == 0
		if(any(l)) grid.rect(x[l], y[l], w[l], h[l], gp = gpar(fill = "#DDDDDD", col = "#DDDDDD"))
	},
	right_annotation = rowAnnotation(Region = country_meta[rownames(m), "region"], 
		                             "#cited" = anno_barplot(sqrt(as.vector(n_cited[rownames(m)])), ylim = c(0, 8000), axis_param = list(at = c(0,2000,4000,6000,8000), labels = c("0", "4M", "16M", "36M", "64M"))),
		                             col = list(Region = region_color)),
	top_annotation = HeatmapAnnotation(Region = country_meta[colnames(m), "region"], 
		                               "#citing" = anno_barplot(sqrt(as.vector(n_citing[colnames(m)])), ylim = c(0, 8000), axis_param = list(at = c(0,2000,4000,6000,8000), labels = c("0", "4M", "16M", "36M", "64M"))),
		                               col = list(Region = region_color)),
	cluster_row_slices = FALSE, cluster_column_slices = FALSE,
	row_split = factor(as.character(mem[rownames(m)])),
	column_split = factor(as.character(mem[colnames(m)])),
	border = "black"

)
draw(ht, merge_legend = TRUE, column_title = "Enrichment of citations between countries",
	heatmap_legend_list = list(Legend(at = "Not available", legend_gp = gpar(fill = "#DDDDDD"))))
```


```{r, fig.width = 12, fig.height = 3}
mem_by_log2_fc = readRDS("country_groups.rds")
mem_by_log2_fc = cola:::relabel_class(mem_by_log2_fc, mem, return_map = FALSE)
mm = rbind(as.character(mem), as.character(mem_by_log2_fc))
colnames(mm) = names(mem)
Heatmap(mm, name = "classification",
	top_annotation = HeatmapAnnotation(Region = country_meta[rownames(m), "region"], 
		                             col = list(Region = region_color)),
	column_order = order(mem, mem_by_log2_fc, country_meta[rownames(m), "region"]),
	col = structure(names = 1:7, 2:8),
	row_labels = c("universe_international", "universe_all"))
```


